-- Active: 1721097763988@@127.0.0.1@3306@admin
CREATE TABLE `user` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'id',
  `username` VARCHAR(50) NOT NULL COMMENT '账号',
  `password` VARCHAR(50) NOT NULL COMMENT '密码',
	`email`      VARCHAR(100) NOT NULL DEFAULT '' COMMENT '邮箱',
	`mobile`     VARCHAR(100) NOT NULL DEFAULT '' COMMENT '手机号',
	`status`     TINYINT(4) NOT NULL DEFAULT '1' COMMENT '状态(0:禁用,1:正常)',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`)
) COMMENT='用户';

CREATE TABLE `menu` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'id',
	`pid`        BIGINT UNSIGNED NOT NULL DEFAULT '0' COMMENT '父id，一级菜单为0',
	`name`      VARCHAR(50)  NOT NULL COMMENT '菜单名称',
	`path`       VARCHAR(200) NOT NULL DEFAULT '' COMMENT '链接',
	`icon`       VARCHAR(50)  NOT NULL DEFAULT '' COMMENT '菜单图标',
	`perms`      VARCHAR(500) NOT NULL DEFAULT '' COMMENT '授权(user:add)',
	`type`       INT NOT NULL COMMENT '类型(1：目录,2：菜单,3：按钮)',
	`sort`       INT NOT NULL DEFAULT '100' COMMENT '排序',
	`status`     INT NOT NULL DEFAULT '1' COMMENT '状态(0:禁用,1:启用,2:隐藏)',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`)
) COMMENT='菜单';